spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food_delivery_db
    username: food_delivery_user
    password: food_delivery_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true